clippy: fix renamed lint
This fixes a clippy hard-failure due to a renamed lint:
```
error: lint `clippy::new_without_default_derive` has been renamed to `clippy::new_without_default`
```